### ISSUE TITLE
E774 RANDOM COMPILER BUG is propagated to execution and is not random

### ISSUE THREAD

**Issue by spartanthe** [jawhitti/INTERCAL#1]
I run into this issue when working with large INTERCAL programs.

Compiled my masterpiece with
`sick.exe monster.i`

I always get this error while executing:
```
C:\~src\jw-sick\INTERCAL\sick\bin\Debug>monster.exe
INTERCAL.Runtime.IntercalException: E774 RANDOM COMPILER BUG
   at monster.Eval(0)
 ---> INTERCAL.Runtime.IntercalException: E774 RANDOM COMPILER BUG
   at INTERCAL.Runtime.Lib.Fail(String errcode) in C:\~src\jw-sick\INTERCAL\intercal.runtime\utils.cs:line 811
   at monster.Eval(ExecutionFrame frame)
   at INTERCAL.Runtime.ExecutionFrame.InternalThreadProc(ExecutionFrame ctx) in C:\~src\jw-sick\INTERCAL\intercal.runtime\twisty.cs:line 92
   --- End of inner exception stack trace ---
   at INTERCAL.Runtime.ExecutionContext.Run(IntercalThreadProc proc) in C:\~src\jw-sick\INTERCAL\intercal.runtime\utils.cs:line 483
   at monster.Run()
   at entry.Main(String[] args)
```
I see 2 issues here:
I001. The bug that is intended to be a compiler bug is propagated to execution.
I002. There is no randomness - if it fails it always fail.

**Comment by jawhitti** [comment]
Thanks for the report.

This is intended behavior. A compiler bug doesn't crash the compiler - it causes the compiler to emit "bad code". If this "bad code" is encountered at runtime it crashes the executable.  That's why you are seeing it consistently.  

```
            //Now we implement E774: RANDOM COMPILER BUG.  The probability of the
            //bug is 1/256 per statement, which is half that of C-Intercal.  See?
            //this compiler is twice as good!
            if (c.Buggy && c.random.Next(256) == 17)
            {
                c.EmitRaw("//E774: RANDOM COMPILER BUG\r\n");
                c.Emit("Lib.Fail(Messages.E774)");
            }
```

If you recompile the code the bug should manifest differently. You can disable bugs via the /b parameter. I wish other compilers I've used would extend the same courtesy.

(EDIT: Big programs are more likely to have the problem)
